# -*- coding: utf-8 -*-
"""FormattedOutput

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xem8LKaScbV19quSgfMpSizWTb4kUlbZ
"""

int1 = int(input("Enter first number: "))
int2 = int(input("Enter second number: "))

sum = int1 + int2
diff = int1 - int2
prod = int1 * int2
intDivision = int1 / int2
average = (int1 + int2) / 2
remainder = int1 % int2
exponent = int1 ** int2

print('Sum:', f'{sum: >18}')
print('Difference:', f'{diff: >11}')
print('Product:', f'{prod: >14}')
print('Integer Division:', f'{intDivision: >5.1f}')
print('Average:', f'{average: >14.2f}')
print('Remainder:', f'{remainder: >12}')
print('Exponent:', f'{exponent: >13,d}')