# -*- coding: utf-8 -*-
"""locker_combination

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nQVxAR0cZuR0U3il6lHy91GGsaIjy5zZ
"""

#Maggie Volker
import random

def lockerCombo():
  myName = "Maggie"
  num1 = random.randint(0, 39)
  num2 = random.randint(0, 39)
  num3 = random.randint(0, 39)
  print(f"{myName}'s locker combination is {num1}-{num2}-{num3}")

  if num1 == num2:
    print("\tPlease try again, this is not a valid combination")
    lockerCombo()
  elif num2 == num3:
    print("\tPlease try again, this is not a valid combination")
    lockerCombo()
  else:
    print("\tThis combination will work")

  return

lockerCombo()