# -*- coding: utf-8 -*-
"""myInfo

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/180IoY_21OLlD1M08ono88-p9wGtlVi33
"""

# CS 175-50
# Maggie Volker
# myInfo

print("Maggie Volker")
print("808 Floral Ln, Honolulu, HI, 80808")
print("732-888-8888")
print("Computer Science")