# -*- coding: utf-8 -*-
"""restaurant_specifications

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bq2Nqs5smN2GIiImndYBho01mKbuQf9t
"""

#CS 175
#Maggie Volker

#set variables
vegetarian = False
vegan = False
gluten_free = False

#display for input
response1 = input("Is anyone in your party a vegetarian?")
#if else
if response1 == "yes":
  vegtarian = True

response2 = input("Is anyone in your party a vegan?")
if response2 == "yes":
  vegan = True

response3 = input("Is anyone in your party gluten-free?")
if response3 == "yes":
  gluten_free = True

#restaurant choices
print("\nHere are your restaurant choices: ")

if not vegetarian and not vegan and not gluten_free:
  print("Joe's Gourmet Burgers")

if not vegan and not gluten_free:
  print("Mama's Fine Italian")

if not vegan:
  print("Main Street Pizza")

print("Corner Cafe")
print("The Chef's Kitchen")